import { Nunito } from "next/font/google";
import "./globals.scss";
import "./layout.scss";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "MoйДневничок",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="wrapper">
          <div className="wrapper__header">
            <Header />
          </div>
          <div className="wrapper__content">{children}</div>
          <div className="wrapper__footer">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
